# Generated by Django 3.2.25 on 2024-06-15 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GrupoZero', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoObra',
            fields=[
                ('cod_estado_obra', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_estado_obra', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='obra',
            name='estado',
            field=models.ForeignKey(db_column='cod_estado_obra', null=True, on_delete=django.db.models.deletion.CASCADE, to='GrupoZero.estadoobra'),
        ),
    ]
