# Generated by Django 3.2.25 on 2024-06-17 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GrupoZero', '0002_auto_20240615_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='rol',
            field=models.ForeignKey(db_column='cod_rol', null=True, on_delete=django.db.models.deletion.CASCADE, to='GrupoZero.rol'),
        ),
    ]
