# Generated by Django 3.2.25 on 2024-06-29 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GrupoZero', '0004_auto_20240629_0343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='obra',
            old_name='user_id',
            new_name='user',
        ),
    ]
